### ISSUE TITLE
Implement video extensions

### ISSUE THREAD

**Issue by romandev** [triplebanana/triple_banana#489]
We should support the following extension features during playing videos.
  - Lock (not allow any inputs during play)
  - Rotate video viewport
  - Full screen
  - PIP (if possible)

**Comment by codeimpl** [comment]
1. lock 구현 해야함 (imageView toggle)
2. mute 구현 (imageView toggle)
3. seekbar 구현 (currentTime, duration)
4. play & pause (imageView toggle)
5. fast forward, fast rewi. nd 구현
