### ISSUE TITLE
Browser lock can be turn on even though no fingerprint registered

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#661]
**Steps to reproduce the problem:**
1. Go to device system setting
2. Remove the fingerprint credential
3. Open the banana browser
4. Go to banana extension settings
5. Turn on the browser lock feature

**What is the expected behavior?**
Can't turn on

**What went wrong?** 
Turn on

**Comment by romandev** [comment]
@knj0426 Could you please investigate this issue?

**Comment by romandev** [comment]
@jdragonbae Could you share reproducible steps?

**Comment by jdragonbae** [comment]
> @jdragonbae Could you share reproducible steps?

Okay. I'll update.

**Comment by knj0426** [comment]
> @knj0426 Could you please investigate this issue?

Okay. I will check. But, I think if there is no biometric information, it will use Keyguard for authentication.
        if (isBiometricsSecure()) {
            return new ActivityBasedBackend(BiometricPromptActivity.class);
        } else if (isKeyguardSecure()) {
            return new ActivityBasedBackend(KeyguardActivity.class);
        }

It should be disabled when there is no biometric and keyguard.

**Comment by romandev** [comment]
@codeimpl If anyone is not working on this issue, I'll take this.

**Comment by knj0426** [comment]
Oh. Sorry. I'm doing in this. While test patch, I foudn several problem. I will upload it intoday
