### ISSUE TITLE
When using secure login in google, a save popup occurs despite saved credential

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#663]
Tested on M OS (Galaxy S7 Edge) 
4.01@85.0.4183.81 / debug / 64bit

**Steps to reproduce the problem:**
1. Login to google
2. Save with secure login
3. Logout
4. Retry login
5. Click logged out ID
6. Authenticate with fingerprint

**What is the expected behavior?**
Nothing

**What went wrong?**
Occur save pop up

**Comment by romandev** [comment]
I can't reproduce this issue. Is this still reproducible on your device?

**Comment by jdragonbae** [comment]
It's seems to be same on N OS (Galaxy S6).
4.01@85.0.4183.81 / debug / 64bit

**Comment by romandev** [comment]
Hmm, I thinYou probably saved your password and ID without @gmail.com postfix. After logout, you would select the ID list provided Google web site and then try to sign-in the stored credentials with authentication. Is my predicition correct?

If so, this is a known issue. Google basically uses the ID as an email format, we can omit the "@gmail.com" postfix for gmail ID. We might fix this issue for Google site but it's difficult to cover general cases. I'm not sure if we should fix this actually. This might be reasonable in perspective of password autofill. WDYT?

**Comment by jdragonbae** [comment]
@romandev Right. Ack.
