### ISSUE TITLE
Pattern authentication show after fingerprint authentication is canceled

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#664]
Tested on M OS (Galaxy S7 Edge) 
4.01@85.0.4183.81 / debug / 64bit

**Steps to reproduce the problem:**
1. Go to https://rsolomakhin.github.io/autofill/
2. Login on the username/Password (Homer_Simpson)
3. Save with secure login
4. Go to https://rsolomakhin.github.io/autofill/
5. Retry to login on the username/Password (Homer_Simpson)
6. Cancel the authentication

**What is the expected behavior?**
Nothing

**What went wrong?**
Show pattern authentication

**Comment by jdragonbae** [comment]
It's seems to be same on N OS (Galaxy S6).
4.01@85.0.4183.81 / debug / 64bit

**Comment by romandev** [comment]
Does the device's biometric sensor work well? In my case, it works well on N-OS

**Comment by jdragonbae** [comment]
The current issue does not seem to be reproduced. When it is reproduced, I will open it again.
