### ISSUE TITLE
Activity is fixed in landscape.

### ISSUE THREAD

**Issue by codeimpl** [triplebanana/triple_banana#668]
When clicking backkey in landscape on media remote, activity is fixed in landscape (O OS 8.0)

**Comment by romandev** [comment]
@codeimpl Could you share reproducible steps in more details?

**Comment by codeimpl** [comment]
It is O os issue(8.0).
If rotate button is off when landscape mode, all application is fixed landscape mode.
It is not triple banana browser issue, so It should be closed.

**Comment by codeimpl** [comment]
It is O os issue(8.0).
If rotate button is off when landscape mode, all application is fixed landscape mode.
It is not triple banana browser issue, so It should be closed.
