### ISSUE TITLE
Enabling the browser lock feature triggeres ApplicationStatus.FOREGROUND

### ISSUE THREAD

**Issue by romandev** [triplebanana/triple_banana#681]
**Reproducible steps**
1. Run Banana Browser
2. Visit Extension Settings
3. Enable Browser Lock feature
4. Click back button (to exit Extension Setting)
5. The `ApplicationStatus.FOREGROUND` event is triggered. It also triggers an authentication.

**Expected**
The `ApplicationStatus.FOREGROUND` should not be triggered.

**Actual**
The `ApplicationStatus.FOREGROUND` event is triggered. It also triggers an authentication.

**Comment by knj0426** [comment]
#686
