### ISSUE TITLE
BrowserLock session doesn't work in case of lock pattern

### ISSUE THREAD

**Issue by knj0426** [triplebanana/triple_banana#685]
1. Register lock pattern on device.(without biometric)
2. launch Triple Banana
3. enter lock pattern.
4. send background app.
5. resume app in 1 minute
6. lock pattern is shown.
In 1 minutes, lock pattern should not be shown..

**Comment by romandev** [comment]
Thank you for reporting this.
This issue is already fixed in https://github.com/triplebanana/triple_banana/pull/680

If not so, please re-open this issue :)
