### ISSUE TITLE
[YouTube Caption] Analyze and test for YouTube caption support

### ISSUE THREAD

**Issue by codeimpl** [triplebanana/triple_banana#882]
Currently, we can't support the YouTube caption on MediaRemote feature. It is because YouTube displays their caption data to their custom caption element. On the other hands, the MediaRemote feature only allows fullscreen video element. So, we should make the MediaRemote include the YouTube caption element when users request video fullscreen mode. So, as a first step, we should analyze the container elements (which contains full screen video element) and test them.

**Comment by romandev** [comment]
```js
// Get list of supported closed captions
document.querySelector(".html5-video-player").getOption("captions", "tracklist");

// Set closed caption (e.g. English)
document.querySelector(".html5-video-player").setOption("captions", "track", {"languageCode": "en"});
```

**Comment by romandev** [comment]
Takes **00:30** for API tests

**Comment by romandev** [comment]
This is very helpful API document:
https://developers.google.com/youtube/iframe_api_reference

**Comment by codeimpl** [comment]
```
// Off closed caption
document.querySelector(".html5-video-player").setOption("captions", "track", {});
```
