### ISSUE TITLE
[Video Downloader] Implement Video Download UI on Media Remote

### ISSUE THREAD

**Issue by codeimpl** [triplebanana/triple_banana#885]
We should implement Video Download UI on Media Remote. To resolve this issue, we should do the following things:
  - Implement UI Icon on Media Remote
  - Send state whether the playing video is downloadable from engine side to browser side

**Comment by romandev** [comment]
Takes 02:20

**Comment by romandev** [comment]
Takes **00:30** to make the video download button show only if the video is downloadable

**Comment by romandev** [comment]
Takes 00:30 to implement the video download API

**Comment by romandev** [comment]
Takes **03:20** totally.

**Comment by codeimpl** [comment]
Thanks for your time update :+1:
