### ISSUE TITLE
[Secure DNS] Resolve conflict with our current implementation

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#888]
Separately present in upstream and Banana Extension for Secure DNS preferences. We have to integrate this.

Through our analysis (#915), we decided behaviors as follows.

| State | Secure Mode | Secure Template | Preference value (secure_dns_switch) |
|-|-|-|-|
| Before first turn on Secure DNS | AUTO | "" | OFF |
| Turns on from off | ON | "1.1.1.1" | ON |

Except for the above two situations, it works the same as upstream Secure DNS.
Additionally, when turn on preference (secure_dns_switch), bypass is also turn on.

Case for app update situations, handling as below.

| feature_name_secure_dns | Secure Mode | Secure Template | Preference value (secure_dns_switch) |
|-|-|-|-|
| OFF | AUTO | "" | OFF |
| ON | ON | "1.1.1.1" | ON |

- [x] Actually in auto mode, If the switch has never been turned on, the preference is off
- [x] When the preference (secure_dns_switch) turns on from off, set mode (secure) and template ("1.1.1.1")
- [ ] Sync Banana Secure DNS switch preference on extension settings & the preference (secure_dns_switch)
- [ ] Implement preference UI in Privacy and Security
- [ ] Migration switch preference for app updates

**Comment by jdragonbae** [comment]
Takes **01:00** for upstream changes.

**Comment by jdragonbae** [comment]
Takes **02:00** for upstream changes (#903).

**Comment by jdragonbae** [comment]
Takes **00:30** for migrating preferences (#905).

**Comment by codeimpl** [comment]
Split this remaining works into #923, #924 and #925
