### ISSUE TITLE
[Youtube Caption] Auto-generated subtitles are not in caption list.

### ISSUE THREAD

**Issue by codeimpl** [triplebanana/triple_banana#912]
We should investigate whether we can get the auto-generated caption list or not first.
To resolve this issue, we should finish the following sub-tasks.
  - [ ] Investigate whether we can get the auto-generated caption list or not (3 hours) 
  - [ ] Implement the caption list API in `YouTubeCommandBuilder` and `YouTubePlayerController` (1 hour)

**Comment by romandev** [comment]
To resolve this issue, we should investigate whether we can get the auto-generated caption list or not.

**Comment by romandev** [comment]
This feature is dropped
