### ISSUE TITLE
[QuickMenu] Requirements analysis

### ISSUE THREAD

**Issue by romandev** [triplebanana/triple_banana#914]
We've checked the feasibility of the Quick Menu feature via a simple prototype (#901, #902). We need to analyze requirements meticulously based on the prototype experience. To resolve this issue, we should write a short requirements document.

- [x] Analyze existing other browsers
- [x] Requirements analysis

**Comment by codeimpl** [comment]
Takes 2 hours for "Analyze existing other browsers"

**Comment by romandev** [comment]
Any update?
