### ISSUE TITLE
[Quick Menu] Writing UML by referring to SRS(Software Requirements Specification)

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#916]
After completed SRS(dependence by @codeimpl), we need to write UML for Quick Menu structure.

**Comment by romandev** [comment]
[![](https://mermaid.ink/img/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gICAgQ29udGFpbmVyIC0tPiBNZW51TGF5b3V0XG4gICAgTWVudUxheW91dCA8fC0tIFRvcEJhclxuICAgIE1lbnVMYXlvdXQgPHwtLSBNaWRkbGVCYXJcbiAgICBNZW51TGF5b3V0IDx8LS0gQm90dG9tQmFyXG4gICAgTWVudUxheW91dCAtLT4gTW9kZWxcbiAgICBNZW51TGF5b3V0IC0tPiBCdXR0b25cbiAgICBCdXR0b24gPHwtLSBOb3JtYWxCdXR0b25cbiAgICBCdXR0b24gPHwtLSBUb2dnbGVCdXR0b25cbiAgICBCdXR0b24gLS0-IEFjdGlvbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG4gICAgQ29udGFpbmVyIC0tPiBNZW51TGF5b3V0XG4gICAgTWVudUxheW91dCA8fC0tIFRvcEJhclxuICAgIE1lbnVMYXlvdXQgPHwtLSBNaWRkbGVCYXJcbiAgICBNZW51TGF5b3V0IDx8LS0gQm90dG9tQmFyXG4gICAgTWVudUxheW91dCAtLT4gTW9kZWxcbiAgICBNZW51TGF5b3V0IC0tPiBCdXR0b25cbiAgICBCdXR0b24gPHwtLSBOb3JtYWxCdXR0b25cbiAgICBCdXR0b24gPHwtLSBUb2dnbGVCdXR0b25cbiAgICBCdXR0b24gLS0-IEFjdGlvbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)
