### ISSUE TITLE
[Media Remote] Need to consider the layout of the media remote buttons in portrait mode

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#919]
As many buttons(CC, Quality, Playback..) are added on Media Remote, there is not enough space in portrait mode.
So, we need to consider the layout of the media remote buttons in portrait mode.

**Comment by jdragonbae** [comment]
<img width="395" alt="Screen Shot 2020-12-13 at 10 43 58 PM" src="https://user-images.githubusercontent.com/34815234/102013629-b53c1580-3d94-11eb-9d86-3b639919e3e8.png">

**Comment by romandev** [comment]
This is unnecessary because the CC feature is dropped.
