### ISSUE TITLE
Fix a bug that the play button doesn't work in media remote

### ISSUE THREAD

**Issue by jdragonbae** [triplebanana/triple_banana#968]
**Reproducible steps:**
1. Build latest version in Release mode
2. Install the release mode APK
3. Play any movie on fullscreen mode with Media Remote
4. "Pause" button click

**Expected behavior**
The "Pause/Play" button should work well.

**Actual behavior**
The "Pause/Play" button doesn't work

**Comment by romandev** [comment]
We decided to revert the related upstream patch.
